### ISSUE TITLE
aes-jsのgit submodule化

### ISSUE THREAD

**Issue by massongit** [marihachi/mist#4]
https://github.com/marihachi/mist/tree/main/vendor/aes-js 以下には https://github.com/ricmoo/aes-js を一部改変したものが配置されているように見受けられます。
以下のようにすると、本リポジトリのaes-jsが本家を改変したものであることやどこを改変しているのかが明瞭になって良いのではないかと思います。

* https://github.com/ricmoo/aes-js をforkし、改変の差分を積む
* forkしたリポジトリを本リポジトリからgit submoduleとして参照する

**Comment by marihachi** [comment]
改変したaes-jsは自分でメンテナンスするべきかか検討しなければなりません。
最初導入時はバンドルサイズの大半をaes-jsが占めていたため、少しでも削るために改変しましたが、
今はReactのバンドルサイズと比べると誤差のレベルです。

今のところ、aes-jsやreactの外部スクリプトはCDNで取得するようにするほうが良いのかなと考えています。

**Comment by massongit** [comment]
>今のところ、aes-jsやreactの外部スクリプトはCDNで取得するようにするほうが良いのかなと考えています。

CDNで本家と同じものを使うようにすれば (本家との差分がなくなれば) 問題なさそうですね。
submodule化はする必要がなさそうということでcloseします。
